import { writable } from 'svelte/store';

export const SUPPORTED = ['en', 'zh', 'ja'];

const en = {
  'brand.title': 'SAVE MIGRATOR',
  'brand.game': 'MONSTER HUNTER RISE · SUNBREAK',
  'brand.tagline': 'Three simple steps — your Switch hunter\'s journey continues on Steam.',
  'brand.items': 'Character · Playtime · Zenny · Points · HR/MR · Items · Gear · Talismans · Decorations · Quest progress · Hunt record',
  'wasm.failed': 'Wasm failed to load.',
      'fs.warn': 'This tool needs the File System Access API — use <b>Chrome or Edge</b> and open the site over localhost or HTTPS (not plain http on a LAN).',
  's0.heading': 'Step 0 · Before You Start',
  's0.desc': '<div class="space-y-1"><p>• <b>Back up your Switch save</b> (needs a homebrew-capable Switch): use <a href="https://github.com/J-D-K/JKSV" target="_blank" rel="noopener noreferrer"><b>JKSV</b></a> to export it — guide: <a href="https://switch.hacks.guide" target="_blank" rel="noopener noreferrer">switch hacking guide</a> — then copy that folder to this computer.</p><p>• <b>On Steam</b>: install <b>Monster Hunter Rise: Sunbreak</b> and create &amp; save at least <b>one character</b> (acts as the migration template).</p></div>',
  's1.heading': 'Step 1 · Switch Save',
  's2.where.title': 'Where is the Steam userdata folder?',
  's2.where.body': 'Usually:<br/>• Windows: <code>C:\\Program Files (x86)\\Steam\\userdata</code><br/>• macOS: <code>~/Library/Application Support/Steam/userdata</code><br/>• Linux: <code>~/.steam/steam/userdata</code><br/>Pick the <code>userdata</code> folder itself (it contains folders named after account IDs).',
  's3.wait': 'Pick your Switch and Steam folders above to see your final slots.',
  's3.noTemplate': 'Your Steam save has no character yet. To migrate a Switch character, you first need one Steam character — start Monster Hunter Rise on Steam, create a character and save once, then come back.',
  's3.hintPick': 'Select both folders above to enable migration.',
  's3.hintPickSwitch': 'Select at least one Switch character to enable migration.',
  'run.cancel': 'Cancel',
  'run.confirmBtn': 'Start migration',
  's2.chars': '{n} character(s)',
's2.noSave': 'no saves',
    'run.pickAccount': 'Pick account again',
  'run.restorePhase': 'Restoring backup…',
  's3.hintWasm': 'Loading the save engine… just a moment.',
    's1.desc': 'Pick the folder with your Switch saves, then tick the characters you want to bring along.',
  's1.pick': 'Choose Switch folder…',
  's1.status': 'Found {n} slot(s). Tick the characters to migrate.',
  's1.noSlots': '✖ No save files found in that folder — make sure you picked the folder with the exported Switch save (files like data001Slot.bin).',
  's3.hintNoSwitch': 'No Switch save found — pick the folder again or check your export.',
    's1.valid': '· OK',
  "s1.unreadable": "· can't read",
  's2.heading': 'Step 2 · Steam Save',
  's2.desc': "Pick your Steam <code>userdata</code> folder — we'll find your saves and recognize your Steam ID.",
  's2.pick': 'Choose Steam userdata folder…',
  's2.folder': 'Folder:',
  's2.account': 'Steam account',
  's2.steamid': 'Steam ID',
  's2.character': '· OK',
  's2.empty': '· empty',
  's2.foundAccount': 'Found account {a} → Steam ID auto-detected.',
  's2.foundDirect': 'Found your save folder directly — Steam ID {id} auto-detected.',
  's2.multi': 'Found {s} Steam account(s) with Monster Hunter Rise saves (out of {n} on this PC) — pick the one with the save.',
  's2.errNoSave': "✖ Couldn't find your Monster Hunter Rise save there. Pick the Steam userdata folder — inside it there should be: <your account number>/1446780/remote/win64_save",
  's2.errNeedId': '✖ You picked the save folder itself. I need your Steam ID to read it — pick the Steam "userdata" folder instead (it auto-detects your ID).',
  'pick.cancelled': 'Picking cancelled.',
  'pick.needChrome': '✖ Need Chrome/Edge (File System Access API).',
  'pick.readErr': '✖ {e}',
  'backups.title': 'Backups',
  'backups.hint': '— auto-saved before every migration & restore',
  'backups.legend': 'Restore = put the game back to that moment (it backs up the current state first). Delete = removes it forever.',
  'backups.none': "No backups yet — they're created automatically before every migration.",
  'backups.loading': 'Reading backups…',
  'backups.files': '{n} file(s) · {kb} KB',
  'backups.tagPrerestore': 'before a restore',
  'backups.restore': 'Restore',
  'backups.delete': 'Delete',
  'backups.confirmRestore': 'Restore backup {name}?\n\nThis overwrites the current Steam save in the game folder. A pre-restore backup is saved first, so you can undo it.',
  'backups.confirmDelete': 'Delete backup {name}? This cannot be undone.',
  'backups.restored': 'Restored {name}. Pre-restore snapshot: {pre}.',
  'backups.restoreFailed': '✖ Restore failed: {e}',
  'backups.deleteFailed': '✖ Delete failed: {e}',
  's3.heading': 'Step 3 · Final Slots',
  's3.desc': "Up to 3 slots — reorder with the arrows. Characters you don't place will be left out (see the note below).",
  's3.pickSwitch': 'Switch characters to migrate',
  's3.pickKeep': 'Steam characters to keep',
  'slot.pos': 'Character {n}',
    's3.warn': 'Steam characters <b>not</b> in your final slots will be moved out (safe in a backup — restore them from the Backups list): {names}',
  's3.slot': 'SLOT {i}',
  's3.fromSwitch': '(from Switch → Steam)',
  's3.kept': '(kept)',
  's3.srcSwitch': 'Switch',
  's3.srcSteam': 'Steam',
  's3.empty': '— empty —',
  's3.moveUp': 'Move up',
  's3.moveDown': 'Move down',
  's3.run': 'Run migration',
  's3.migrating': 'Migrating…',
  'msg.maxSlots': 'Only 3 slots — untick something first.',
  'msg.reading': 'Reading saves…',
  'msg.done': 'Done',
  'run.title': 'Ready for the next quest, Hunter?',
  'run.backupFirst': '• Your current Steam save is backed up first (backup_<timestamp> in win64_save).',
  'run.finalSlots': 'Final slots:',
  'run.removed': '• Will be moved out (safe in backup): {names}',
  'run.steamId': '• Steam ID: {id}',
  'run.cloud': 'Important: quit the game and let Steam Cloud finish syncing before continuing.',
  'run.switchChar': 'Switch character ({name})',
  'run.keptChar': 'Kept Steam character ({name})',
  'run.empty': 'empty',
  'run.wrongCount': 'You selected {n} characters; only 3 slots allowed. Remove {extra} before migrating.',
  'run.slotNeeds': 'Slot {i} needs a Steam character as a base — none found. Create one in Rise on Steam (or keep one of your Steam slots), then try again. Nothing was changed ({backup} is safe).',
  'run.migratePhase': 'Migrating {name} → Slot {i}…',
  'run.couldNotRead': "Couldn't read {name} — aborting (nothing lost; backup: {backup}).",
  'run.diffAcc': "Couldn't read your Steam save with Steam ID {id} — it may belong to a different Steam account. Nothing was written; your files are safe in backup {backup}. Use 'Choose Steam userdata folder' again and pick your account.",
  'res.complete': 'Migration complete!',
  'res.flavor': 'The new gathering hub is ready — welcome back, Hunter.',
  'res.backup': '• Backup:',
  'res.next': 'Next: quit the game → reopen → load your characters.',
  'res.verifyOk': 'All good — done!',
  'res.restoreNow': 'Wrong? Roll back to the backup',
  'why.template': 'A Steam-version character is needed as the base (the migration uses its framework). Create one in Rise on Steam first.',
  'rail.prep': 'Prep',
  'rail.switch': 'Switch',
  'wiz.back': 'Back',
  'wiz.next': 'Next',
  'wiz.last': 'Last step — check the layout above and go!',
  'intro.title': 'Welcome! Move your save in three steps',
  'intro.skip': 'Skip',
  'intro.next': 'Next',
  'intro.start': "Let's go!",
  'intro.s1': '① Export the save from your Switch (JKSV — needs a homebrew-capable Switch).',
  'intro.s2': '② Pick your Steam userdata folder — your Steam ID and saves are found automatically.',
  'intro.s3': "③ Check the layout (you can reorder), then press Start migration.",
  'intro.s4': "Afterwards: quit the game → reopen → load. You can always restore from a backup.",
  'res.verify': 'Auto-check',
  'scan.reading': 'Reading Steam save {n}/{total}…',
  'scan.loading': 'Working…',
  
    'rail.steam': 'Steam',
  'rail.layout': 'Layout',
    'res.wWrittenSwitch': '{target} ← Switch {name}',
  'res.wWrittenKept': '{target} ← kept (was {name})',
  'res.wWrittenEmpty': '{target} ← empty',
  'res.errGeneric': '{e}',
  'footer.private': 'Runs entirely in your browser — files never uploaded anywhere.',
  'footer.tribute': 'With appreciation to the framework this tool is built upon:'
};

const zh = {
  'brand.title': 'SAVE MIGRATOR',
  'brand.game': 'MONSTER HUNTER RISE · SUNBREAK',
  'brand.tagline': '简单三步，让你的 Switch 猎人生涯在 Steam 完美延续。',
  'brand.items': '角色形象 · 时长 · 金钱 · 点数 · HR/MR · 道具 · 装备 · 护石 · 装饰品 · 任务进度 · 狩猎记录',
  'wasm.failed': 'WebAssembly 加载失败。',
      'fs.warn': '本工具需要文件系统访问 API——请使用 <b>Chrome 或 Edge</b>，并通过 localhost 或 HTTPS 打开（请勿用普通 http 局域网地址）。',
  's0.heading': '第 0 步 · 开始前',
  's0.desc': '<div class="space-y-1"><p>• <b>导出 Switch 存档</b>（需一台<b>可破解/自制系统的 Switch</b>）：用 <a href="https://github.com/J-D-K/JKSV" target="_blank" rel="noopener noreferrer"><b>JKSV</b></a> 导出（教程：<a href="https://switch.hacks.guide" target="_blank" rel="noopener noreferrer">switch.hacks.guide</a>），然后把该文件夹拷到本机。</p><p>• <b>Steam</b>：安装 <b>MH Rise：曙光</b>，并<b>创建并保存至少一个角色</b>（作为迁移模板）。</p></div>',
  's1.heading': '第一步 · Switch 存档',
  's2.where.title': 'Steam userdata 文件夹在哪？',
  's2.where.body': '通常在：<br/>• Windows：<code>C:\\Program Files (x86)\\Steam\\userdata</code><br/>• macOS：<code>~/Library/Application Support/Steam/userdata</code><br/>• Linux：<code>~/.steam/steam/userdata</code><br/>选择 <code>userdata</code> 文件夹本身（里面是按账号 ID 命名的文件夹）。',
  's3.wait': '先在上方选择 Switch 与 Steam 的存档文件夹，才能看到最终槽位。',
  's3.noTemplate': '你的 Steam 存档里还没有角色。要迁移 Switch 角色，需要先有一个 Steam 角色——在 Steam 版启动游戏，创建一个角色并保存一次，再回来。',
  's3.hintPick': '请先在上方选好两个文件夹，才能迁移。',
  's3.hintPickSwitch': '请先在上方勾选至少一个 Switch 角色。',
  'run.cancel': '取消',
  'run.confirmBtn': '开始迁移',
  's2.chars': '{n} 个角色',
's2.noSave': '无存档',
    'run.pickAccount': '重新选择账号',
  'run.restorePhase': '正在恢复备份…',
  's3.hintWasm': '引擎加载中，请稍候……',
    's1.desc': '选择你 Switch 存档所在的文件夹，然后勾选想带走的角色。',
  's1.pick': '选择 Switch 文件夹…',
  's1.status': '找到 {n} 个存档位。勾选要迁移的角色吧。',
  's1.noSlots': '✖ 该文件夹里没有找到存档文件——请确认选的是导出的 Switch 存档文件夹（包含 data001Slot.bin 等文件）。',
  's3.hintNoSwitch': '没找到 Switch 存档——请重新选择文件夹，或检查导出内容。',
    's1.valid': '· 正常',
  's1.unreadable': '· 无法读取',
  's2.heading': '第二步 · Steam 存档',
  's2.desc': '选择你的 Steam <code>userdata</code> 文件夹——我们会找到存档，并自动认出你的 Steam ID。',
  's2.pick': '选择 Steam userdata 文件夹…',
  's2.folder': '文件夹：',
  's2.account': 'Steam 账号',
  's2.steamid': 'Steam ID',
  's2.character': '· 正常',
  's2.empty': '· 空',
  's2.foundAccount': '已找到账号 {a}，Steam ID 已自动识别。',
  's2.foundDirect': '直接找到了你的存档文件夹——已自动识别 Steam ID {id}。',
  's2.multi': '在这台电脑上找到 {n} 个 Steam 用户，其中 {s} 个有怪物猎人：崛起存档——请选择有存档的那个。',
  's2.errNoSave': '✖ 这里没有找到怪物猎人：崛起的存档。请选 Steam userdata 文件夹（里面应有 <你的账号数字>/1446780/remote/win64_save）。',
  's2.errNeedId': '✖ 你选的是存档文件夹本身。我还需要你的 Steam ID 才能读取——请改选 Steam "userdata" 文件夹（会自动认出你的 ID）。',
  'pick.cancelled': '已取消选择。',
  'pick.needChrome': '✖ 需要 Chrome/Edge（文件系统访问 API）。',
  'pick.readErr': '✖ {e}',
  'backups.title': '备份',
  'backups.hint': '——每次迁移与恢复前自动保存',
  'backups.legend': '恢复 = 把游戏放回那个时刻（会先备份现在）。删除 = 永久删除。',
  'backups.none': '还没有备份——每次迁移前都会自动创建。',
  'backups.loading': '正在读取备份…',
  'backups.files': '{n} 个文件 · {kb} KB',
  'backups.tagPrerestore': '恢复前',
  'backups.restore': '恢复',
  'backups.delete': '删除',
  'backups.confirmRestore': '恢复备份 {name}？\n\n这会覆盖游戏文件夹里当前的 Steam 存档。会先保存一份「恢复前」备份，所以还能反悔。',
  'backups.confirmDelete': '删除备份 {name}？此操作无法撤销。',
  'backups.restored': '已恢复 {name}。恢复前快照：{pre}。',
  'backups.restoreFailed': '✖ 恢复失败：{e}',
  'backups.deleteFailed': '✖ 删除失败：{e}',
  's3.heading': '第三步 · 最终槽位',
  's3.desc': '最多 3 个槽位——用箭头排好顺序。没放进去的角色会被移出（见下方提醒）。',
  's3.pickSwitch': '要迁移的 Switch 角色',
  's3.pickKeep': '要保留的 Steam 角色',
  'slot.pos': '角色 {n}',
    's3.warn': '未放入最终槽位的 Steam 角色会被<b>移出</b>槽位（仍安全保存在备份里——可从「备份」列表恢复）：{names}',
  's3.slot': '槽位 {i}',
  's3.fromSwitch': '（来自 Switch → Steam）',
  's3.kept': '（保留）',
  's3.srcSwitch': 'Switch',
  's3.srcSteam': 'Steam',
  's3.empty': '— 空 —',
  's3.moveUp': '上移',
  's3.moveDown': '下移',
  's3.run': '开始迁移',
  's3.migrating': '迁移中…',
  'msg.maxSlots': '最多 3 个槽位——先取消一个吧。',
  'msg.reading': '正在读取存档…',
  'msg.done': '完成',
  'run.title': '准备好了出发吗，猎人？',
  'run.backupFirst': '• 会先备份当前的 Steam 存档（win64_save 里的 backup_<时间戳>）。',
  'run.finalSlots': '最终槽位：',
  'run.removed': '• 将被移出槽位（备份里有）：{names}',
  'run.steamId': '• Steam ID：{id}',
  'run.cloud': '重要：先退出游戏，等 Steam 云同步完成再继续。',
  'run.switchChar': 'Switch 角色（{name}）',
  'run.keptChar': '保留的 Steam 角色（{name}）',
  'run.empty': '空',
  'run.wrongCount': '选了 {n} 个角色，最多 3 个。请先移除 {extra} 个。',
  'run.slotNeeds': '槽位 {i} 需要一个 Steam 角色作为基底——未找到。请先在 Steam 版创建一个角色（或保留一个 Steam 槽位），再试一次。未做任何改动（备份 {backup} 安全）。',
  'run.migratePhase': '正在迁移 {name} → 槽位 {i}…',
  'run.couldNotRead': '无法读取 {name}——已中止（什么都没丢，备份：{backup}）。',
  'run.diffAcc': '用 Steam ID {id} 读不出这份存档——它可能属于另一个 Steam 账号。什么都没写入；文件在备份 {backup} 里很安全。请再次点击「选择 Steam userdata 文件夹」并选择你的账号。',
  'res.complete': '迁移完成！',
  'res.flavor': '新据点已经收拾好了——欢迎回来，猎人。',
  'res.backup': '• 备份：',
  'res.next': '下一步：关闭游戏 → 重新打开 → 加载你的角色。',
  'res.verifyOk': '验证成功，收工！',
  'res.restoreNow': '不对？回滚到备份',
  'why.template': '需要一个 Steam 版角色作为基底（迁移会套用它的框架）。请先在 Steam 版创建一个角色。',
  'rail.prep': '准备',
  'rail.switch': 'Switch',
  'wiz.back': '上一步',
  'wiz.next': '下一步',
  'wiz.last': '最后一步：确认上方布局后出发！',
  'intro.title': '欢迎！三步搬走你的存档',
  'intro.skip': '跳过',
  'intro.next': '下一步',
  'intro.start': '开始使用！',
  'intro.s1': '① 从 Switch 导出存档（JKSV——需要可运行 homebrew 的 Switch）。',
  'intro.s2': '② 选择 Steam userdata 文件夹——自动识别 Steam ID 并找到存档。',
  'intro.s3': '③ 检查布局（可排序），然后点「开始迁移」。',
  'intro.s4': '完成后：关闭游戏 → 重开 → 加载角色。随时可从备份恢复。',
  'res.verify': '自动校验',
  'scan.reading': '正在读取 Steam 存档 {n}/{total}…',
  'scan.loading': '处理中…',
  
    'rail.steam': 'Steam',
  'rail.layout': '布局',
    'res.wWrittenSwitch': '{target} ← Switch 角色 {name}',
  'res.wWrittenKept': '{target} ← 保留（原为 {name}）',
  'res.wWrittenEmpty': '{target} ← 清空',
  'res.errGeneric': '{e}',
  'footer.private': '一切都在浏览器里完成——文件不会上传到任何地方。',
  'footer.tribute': '致敬本工具所依托的框架：'
};

const ja = {
  'brand.title': 'SAVE MIGRATOR',
  'brand.game': 'MONSTER HUNTER RISE · SUNBREAK',
  'brand.tagline': '簡単3ステップで、Switchの狩りの日々をSteamでそのまま続けよう。',
  'brand.items': 'キャラ · プレイ時間 · ゼニー · ポイント · HR/MR · アイテム · 装備 · 護石 · 装飾品 · クエスト進行 · 狩猟記録',
  'wasm.failed': 'WebAssembly の読み込みに失敗しました。',
      'fs.warn': 'このツールには File System Access API が必要です——<b>Chrome/Edge</b> を使用し、localhost または HTTPS で開いてください。',
  's0.heading': '手順0・始める前に',
  's0.desc': '<div class="space-y-1"><p>• <b>Switchのセーブを書き出す</b>（<b>改造Switch</b>が必要）：<a href="https://github.com/J-D-K/JKSV" target="_blank" rel="noopener noreferrer"><b>JKSV</b></a>でエクスポート（ガイド：<a href="https://switch.hacks.guide" target="_blank" rel="noopener noreferrer">switch.hacks.guide</a>）、そしてそのフォルダをこのPCへコピー。</p><p>• <b>Steam</b>：<b>MH Rise：サンブレイク</b>を入れて、<b>キャラを1体以上作って保存</b>（移行テンプレート）。</p></div>',
  's1.heading': '手順1・Switch セーブ',
  's2.where.title': 'Steam userdata フォルダーはどこ？',
  's2.where.body': '通常は：<br/>• Windows：<code>C:\\Program Files (x86)\\Steam\\userdata</code><br/>• macOS：<code>~/Library/Application Support/Steam/userdata</code><br/>• Linux：<code>~/.steam/steam/userdata</code><br/><code>userdata</code> フォルダー自体を選んでください（アカウント ID のフォルダーが並んでいます）。',
  's3.wait': '先に上のフォルダーを選択すると、最終スロットが表示されます。',
  's3.noTemplate': 'Steam 側にキャラがまだいません。Switch キャラを移すには、まず Steam 版でキャラを1体作成・保存してから戻ってきてください。',
  's3.hintPick': 'まず上のフォルダーを両方選ぶと移行できます。',
  's3.hintPickSwitch': '上の Switch キャラを1体以上チェックすると移行できます。',
  'run.cancel': 'キャンセル',
  'run.confirmBtn': '移行を開始',
  's2.chars': '{n} キャラ',
's2.noSave': 'セーブなし',
    'run.pickAccount': 'アカウントを選び直す',
  'run.restorePhase': 'バックアップを復元中…',
  's3.hintWasm': 'エンジンを読み込み中……少々お待ちください。',
    's1.desc': 'Switch のセーブがあるフォルダーを選び、連れて行くキャラにチェックを。',
  's1.pick': 'Switch フォルダーを選択…',
  's1.status': '{n} 件のスロットを発見。移行するキャラにチェックを。',
  's1.noSlots': '✖ このフォルダーにセーブが見つかりません——書き出した Switch セーブ（data001Slot.bin など）のあるフォルダーか確認してください。',
  's3.hintNoSwitch': 'Switch セーブが見つかりません——フォルダーを選び直すか、書き出しを確認してください。',
    's1.valid': '· 問題なし',
  's1.unreadable': '· 読込不可',
  's2.heading': '手順2・Steam セーブ',
  's2.desc': 'Steam の <code>userdata</code> フォルダーを選ぼう——セーブを見つけて Steam ID も自動でわかる。',
  's2.pick': 'Steam userdata フォルダーを選択…',
  's2.folder': 'フォルダー：',
  's2.account': 'Steam アカウント',
  's2.steamid': 'Steam ID',
  's2.character': '· 問題なし',
  's2.empty': '· 空',
  's2.foundAccount': 'アカウント {a} を発見 → Steam ID を自動判定しました。',
  's2.foundDirect': 'セーブフォルダーを直接発見——Steam ID {id} を自動判定しました。',
  's2.multi': 'このPCに {n} 件の Steam ユーザー、うち {s} 件にMHライズのセーブがあります——セーブのある方を選んでください。',
  's2.errNoSave': '✖ ここにMHライズのセーブは無い。Steam userdata フォルダーを選んで（中に <お使いのアカウント番号>/1446780/remote/win64_save があるはず）。',
  's2.errNeedId': '✖ セーブフォルダー自体を選んでいます。読み取りには Steam ID が必要です——Steam "userdata" フォルダーを選んでください（ID は自動判定されます）。',
  'pick.cancelled': '選択をキャンセルしました。',
  'pick.needChrome': '✖ Chrome/Edge が必要です（File System Access API）。',
  'pick.readErr': '✖ {e}',
  'backups.title': 'バックアップ',
  'backups.hint': '——移行・復元の前に毎回自動保存',
  'backups.legend': '「復元」= その時点のゲームに戻す（今の状態を先にバックアップ）。「削除」= 完全に削除。',
  'backups.none': 'まだバックアップはありません——移行の前に毎回自動で保存されます。',
  'backups.loading': 'バックアップを読み込み中…',
  'backups.files': '{n} ファイル · {kb} KB',
  'backups.tagPrerestore': '復元前',
  'backups.restore': '復元',
  'backups.delete': '削除',
  'backups.confirmRestore': '{name} を復元しますか？\n\nゲームフォルダー内の現在の Steam セーブを上書きします。「復元前」バックアップを先に保存するので、取り消せます。',
  'backups.confirmDelete': '{name} を削除しますか？この操作は取り消せません。',
  'backups.restored': '{name} を復元しました。復元前スナップショット：{pre}。',
  'backups.restoreFailed': '✖ 復元に失敗しました：{e}',
  'backups.deleteFailed': '✖ 削除に失敗しました：{e}',
  's3.heading': '手順3・最終スロット',
  's3.desc': '最大3スロット——矢印で並べ替え。入れなかったキャラは外れる（下の注意参照）。',
  's3.pickSwitch': '移す Switch キャラ',
  's3.pickKeep': '残す Steam キャラ',
  'slot.pos': 'キャラ {n}',
    's3.warn': '最終スロットに<b>入っていない</b> Steam キャラは、スロットから外れます（バックアップに保存——「バックアップ」一覧から復元できます）：{names}',
  's3.slot': 'スロット {i}',
  's3.fromSwitch': '（Switch → Steam）',
  's3.kept': '（残す）',
  's3.srcSwitch': 'Switch',
  's3.srcSteam': 'Steam',
  's3.empty': '— 空 —',
  's3.moveUp': '上へ',
  's3.moveDown': '下へ',
  's3.run': '移行開始',
  's3.migrating': '移行中…',
  'msg.maxSlots': '最大3スロット——先に一つ外して。',
  'msg.reading': 'セーブを読み込み中…',
  'msg.done': '完了',
  'run.title': '次のクエストへ、準備はいいか？',
  'run.backupFirst': '• 現在の Steam セーブを最初にバックアップします（win64_save 内の backup_<タイムスタンプ>）。',
  'run.finalSlots': '最終スロット：',
  'run.removed': '• スロットから外れるもの（バックアップに保存）：{names}',
  'run.steamId': '• Steam ID：{id}',
  'run.cloud': '重要：ゲームを終了し、Steam クラウドの同期が終わってから続行してください。',
  'run.switchChar': 'Switch キャラ（{name}）',
  'run.keptChar': '残す Steam キャラ（{name}）',
  'run.empty': '空',
  'run.wrongCount': '{n} キャラを選択しています。スロットは3つまで。{extra} つ外してから移行してください。',
  'run.slotNeeds': 'スロット {i} の土台となる Steam キャラが見つかりません。先に Steam 版でキャラを作るか、Steam のスロットを残してください。何も変更されていません（{backup} は安全です）。',
  'run.migratePhase': '{name} を移行中 → スロット {i}…',
  'run.couldNotRead': '{name} を読み込めません——中止しました（何も失われていません。バックアップ：{backup}）。',
  'run.diffAcc': 'Steam ID {id} ではセーブを読み込めません——別の Steam アカウントの可能性があります。何も書き込まれていません。ファイルはバックアップ {backup} に安全です。もう一度「Steam userdata フォルダーを選択」から正しいアカウントを選んでください。',
  'res.complete': '移行完了！',
  'res.flavor': '新しい拠点の準備も整った——おかえり、ハンター。',
  'res.backup': '• バックアップ：',
  'res.next': '次：ゲームを終了 → 再起動 → キャラをロード。',
  'res.verifyOk': '確認OK、完了！',
  'res.restoreNow': 'おかしい？バックアップに戻す',
  'why.template': 'Steam 版のキャラが土台として必要です（移行はその枠組みを使います）。先に Steam 版で作成してください。',
  'rail.prep': '準備',
  'rail.switch': 'Switch',
  'wiz.back': '戻る',
  'wiz.next': '次へ',
  'wiz.last': '最終チェック——上のレイアウトを確認して出発！',
  'intro.title': 'ようこそ！3ステップでお引っ越し',
  'intro.skip': 'スキップ',
  'intro.next': '次へ',
  'intro.start': 'はじめよう！',
  'intro.s1': '① Switch からセーブを書き出す（JKSV——homebrew 対応機が必要）。',
  'intro.s2': '② Steam userdata フォルダーを選択——Steam ID とセーブは自動で判定。',
  'intro.s3': '③ レイアウトを確認（並べ替え可）→「移行開始」。',
  'intro.s4': '完了後：ゲーム終了 → 再起動 → キャラをロード。いつでもバックアップから復元できます。',
  'res.verify': '自動チェック',
  'scan.reading': 'Steam セーブを読込中 {n}/{total}…',
  'scan.loading': '処理中…',
  
    'rail.steam': 'Steam',
  'rail.layout': 'レイアウト',
    'res.wWrittenSwitch': '{target} ← Switch キャラ {name}',
  'res.wWrittenKept': '{target} ← 残す（元 {name}）',
  'res.wWrittenEmpty': '{target} ← 空に',
  'res.errGeneric': '{e}',
  'footer.private': 'すべてブラウザ内で完結——アップロードは一切なし。',
  'footer.tribute': '本ツールの土台となったフレームワークに敬意を：'
};

export const messages = { en, zh, ja };

export const locale = writable('en');

export function setLocale(l) {
  if (!SUPPORTED.includes(l)) l = 'en';
  locale.set(l);
  if (typeof localStorage !== 'undefined') localStorage.setItem('mhsave_locale', l);
}

export function initLocale() {
  const s = typeof localStorage !== 'undefined' ? localStorage.getItem('mhsave_locale') : null;
  if (SUPPORTED.includes(s)) { locale.set(s); return; }
  const nav = (typeof navigator !== 'undefined' && navigator.language) || '';
  let l = nav.startsWith('zh') ? 'zh' : nav.startsWith('ja') ? 'ja' : 'en';
  if (!SUPPORTED.includes(l)) l = 'en';
  locale.set(l);
}

export function fmt(key, vars, lang) {
  let s = (messages[lang] && messages[lang][key]) ?? messages.en[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}
